In [1]:
import os, requests
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("API_KEY")
API_URL = "https://api.weatherapi.com/v1/forecast.json"

import pandas as pd

In [2]:
def get_weather(city: str, days: int, url=API_URL, key=API_KEY):
    data = {}
    parameters = {'key':key, 'q':city, 'days':days}
    response = requests.get(url, params=parameters)
    
    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()
    else:
        print(f"Error fetching {city}.\n Response: {response.status_code}")
    return data

In [3]:
weather_data = get_weather('Varadero', 3)

In [4]:
weather_data['forecast']

{'forecastday': [{'date': '2026-05-01',
   'date_epoch': 1777593600,
   'day': {'maxtemp_c': 33.7,
    'maxtemp_f': 92.7,
    'mintemp_c': 22.7,
    'mintemp_f': 72.9,
    'avgtemp_c': 27.4,
    'avgtemp_f': 81.4,
    'maxwind_mph': 16.6,
    'maxwind_kph': 26.6,
    'totalprecip_mm': 0.0,
    'totalprecip_in': 0.0,
    'totalsnow_cm': 0.0,
    'avgvis_km': 10.0,
    'avgvis_miles': 6.0,
    'avghumidity': 76,
    'daily_will_it_rain': 0,
    'daily_chance_of_rain': 0,
    'daily_will_it_snow': 0,
    'daily_chance_of_snow': 0,
    'condition': {'text': 'Sunny',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
     'code': 1000},
    'uv': 11.8},
   'astro': {'sunrise': '06:52 AM',
    'sunset': '07:53 PM',
    'moonrise': '08:07 PM',
    'moonset': '06:31 AM',
    'moon_phase': 'Full Moon',
    'moon_illumination': 99,
    'is_moon_up': 1,
    'is_sun_up': 0},
   'hour': [{'time_epoch': 1777608000,
     'time': '2026-05-01 00:00',
     'temp_c': 25.0,
     'temp_f': 76.9,
     'is_day': 0,
     'condition': {'text': 'Clear',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
      'code': 1000},
     'wind_mph': 6.9,
     'wind_kph': 11.2,
     'wind_degree': 96,
     'wind_dir': 'E',
     'pressure_mb': 1013.0,
     'pressure_in': 29.91,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 82,
     'cloud': 0,
     'feelslike_c': 27.2,
     'feelslike_f': 81.0,
     'windchill_c': 25.0,
     'windchill_f': 76.9,
     'heatindex_c': 27.2,
     'heatindex_f': 81.0,
     'dewpoint_c': 21.5,
     'dewpoint_f': 70.7,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 10.6,
     'gust_kph': 17.1,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1777611600,
     'time': '2026-05-01 01:00',
     'temp_c': 24.6,
     'temp_f': 76.3,
     'is_day': 0,
     'condition': {'text': 'Clear',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
      'code': 1000},
     'wind_mph': 6.3,
     'wind_kph': 10.1,
     'wind_degree': 100,
     'wind_dir': 'E',
     'pressure_mb': 1013.0,
     'pressure_in': 29.91,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 84,
     'cloud': 0,
     'feelslike_c': 26.8,
     'feelslike_f': 80.2,
     'windchill_c': 24.6,
     'windchill_f': 76.3,
     'heatindex_c': 26.8,
     'heatindex_f': 80.2,
     'dewpoint_c': 21.7,
     'dewpoint_f': 71.1,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 9.7,
     'gust_kph': 15.6,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1777615200,
     'time': '2026-05-01 02:00',
     'temp_c': 24.1,
     'temp_f': 75.4,
     'is_day': 0,
     'condition': {'text': 'Clear',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
      'code': 1000},
     'wind_mph': 5.8,
     'wind_kph': 9.4,
     'wind_degree': 113,
     'wind_dir': 'ESE',
     'pressure_mb': 1012.0,
     'pressure_in': 29.89,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 86,
     'cloud': 0,
     'feelslike_c': 26.3,
     'feelslike_f': 79.3,
     'windchill_c': 24.1,
     'windchill_f': 75.4,
     'heatindex_c': 26.3,
     'heatindex_f': 79.3,
     'dewpoint_c': 21.7,
     'dewpoint_f': 71.1,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 9.4,
     'gust_kph': 15.2,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1777618800,
     'time': '2026-05-01 03:00',
     'temp_c': 23.5,
     'temp_f': 74.4,
     'is_day': 0,
     'condition': {'text': 'Clear',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
      'code': 1000},
     'wind_mph': 5.1,
     'wind_kph': 8.3,
     'wind_degree': 107,
     'wind_dir': 'ESE',
     'pressure_mb': 1011.0,
     'pressure_in': 29.87,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 88,
     'cloud': 1,
     'feelslike_c': 25.8,
     'feelslike_f': 78.4,
     'windchill_c': 23.5,
     'windchill_f': 74.4,
     'heatindex_c': 25.8,
     'heatindex_f': 78.4,
     'dewpoint_c': 21.5,
     'dewpoint_f': 70.7,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 8.4,
     'gust_kph': 13.6,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1777622400,
     'time': '2026-05-01 04:00',
     'temp_c': 23.2,
     'temp_f': 73.7,
     'is_day': 0,
     'condition': {'text': 'Clear',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
      'code': 1000},
     'wind_mph': 4.0,
     'wind_kph': 6.5,
     'wind_degree': 97,
     'wind_dir': 'E',
     'pressure_mb': 1011.0,
     'pressure_in': 29.86,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 90,
     'cloud': 2,
     'feelslike_c': 25.4,
     'feelslike_f': 77.7,
     'windchill_c': 23.2,
     'windchill_f': 73.7,
     'heatindex_c': 25.4,
     'heatindex_f': 77.7,
     'dewpoint_c': 21.2,
     'dewpoint_f': 70.2,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 6.6,
     'gust_kph': 10.7,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1777626000,
     'time': '2026-05-01 05:00',
     'temp_c': 22.9,
     'temp_f': 73.3,
     'is_day': 0,
     'condition': {'text': 'Clear',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
      'code': 1000},
     'wind_mph': 4.9,
     'wind_kph': 7.9,
     'wind_degree': 124,
     'wind_dir': 'SE',
     'pressure_mb': 1011.0,
     'pressure_in': 29.87,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 88,
     'cloud': 1,
     'feelslike_c': 25.2,
     'feelslike_f': 77.3,
     'windchill_c': 22.9,
     'windchill_f': 73.3,
     'heatindex_c': 25.2,
     'heatindex_f': 77.3,
     'dewpoint_c': 20.8,
     'dewpoint_f': 69.4,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 8.0,
     'gust_kph': 12.9,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1777629600,
     'time': '2026-05-01 06:00',
     'temp_c': 23.8,
     'temp_f': 74.8,
     'is_day': 0,
     'condition': {'text': 'Clear',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
      'code': 1000},
     'wind_mph': 3.4,
     'wind_kph': 5.4,
     'wind_degree': 104,
     'wind_dir': 'ESE',
     'pressure_mb': 1012.0,
     'pressure_in': 29.88,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 87,
     'cloud': 2,
     'feelslike_c': 26.0,
     'feelslike_f': 78.8,
     'windchill_c': 23.8,
     'windchill_f': 74.8,
     'heatindex_c': 26.0,
     'heatindex_f': 78.8,
     'dewpoint_c': 20.5,
     'dewpoint_f': 68.9,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 5.5,
     'gust_kph': 8.9,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1777633200,
     'time': '2026-05-01 07:00',
     'temp_c': 24.8,
     'temp_f': 76.6,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 3.1,
     'wind_kph': 5.0,
     'wind_degree': 105,
     'wind_dir': 'ESE',
     'pressure_mb': 1012.0,
     'pressure_in': 29.9,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 84,
     'cloud': 1,
     'feelslike_c': 27.1,
     'feelslike_f': 80.7,
     'windchill_c': 24.8,
     'windchill_f': 76.6,
     'heatindex_c': 27.1,
     'heatindex_f': 80.7,
     'dewpoint_c': 21.7,
     'dewpoint_f': 71.0,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 5.1,
     'gust_kph': 8.2,
     'uv': 0.0,
     'short_rad': 0.04,
     'diff_rad': 0.02,
     'dni': 0.03,
     'gti': 0.04},
    {'time_epoch': 1777636800,
     'time': '2026-05-01 08:00',
     'temp_c': 26.1,
     'temp_f': 79.0,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 3.6,
     'wind_kph': 5.8,
     'wind_degree': 119,
     'wind_dir': 'ESE',
     'pressure_mb': 1013.0,
     'pressure_in': 29.92,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 79,
     'cloud': 2,
     'feelslike_c': 28.5,
     'feelslike_f': 83.4,
     'windchill_c': 26.1,
     'windchill_f': 79.0,
     'heatindex_c': 28.5,
     'heatindex_f': 83.4,
     'dewpoint_c': 21.9,
     'dewpoint_f': 71.4,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 4.9,
     'gust_kph': 8.0,
     'uv': 0.4,
     'short_rad': 10.75,
     'diff_rad': 5.53,
     'dni': 5.6,
     'gti': 9.95},
    {'time_epoch': 1777640400,
     'time': '2026-05-01 09:00',
     'temp_c': 27.5,
     'temp_f': 81.6,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 4.3,
     'wind_kph': 6.8,
     'wind_degree': 103,
     'wind_dir': 'ESE',
     'pressure_mb': 1014.0,
     'pressure_in': 29.93,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 71,
     'cloud': 2,
     'feelslike_c': 30.2,
     'feelslike_f': 86.4,
     'windchill_c': 27.5,
     'windchill_f': 81.6,
     'heatindex_c': 30.2,
     'heatindex_f': 86.4,
     'dewpoint_c': 21.8,
     'dewpoint_f': 71.2,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 5.3,
     'gust_kph': 8.5,
     'uv': 1.7,
     'short_rad': 290.14,
     'diff_rad': 82.06,
     'dni': 211.01,
     'gti': 261.17},
    {'time_epoch': 1777644000,
     'time': '2026-05-01 10:00',
     'temp_c': 30.4,
     'temp_f': 86.7,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 5.1,
     'wind_kph': 8.3,
     'wind_degree': 96,
     'wind_dir': 'E',
     'pressure_mb': 1014.0,
     'pressure_in': 29.93,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 64,
     'cloud': 2,
     'feelslike_c': 35.0,
     'feelslike_f': 95.0,
     'windchill_c': 30.4,
     'windchill_f': 86.7,
     'heatindex_c': 35.0,
     'heatindex_f': 95.0,
     'dewpoint_c': 21.6,
     'dewpoint_f': 70.9,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 6.1,
     'gust_kph': 9.8,
     'uv': 4.2,
     'short_rad': 412.62,
     'diff_rad': 79.5,
     'dni': 340.4,
     'gti': 368.23},
    {'time_epoch': 1777647600,
     'time': '2026-05-01 11:00',
     'temp_c': 32.0,
     'temp_f': 89.7,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 6.0,
     'wind_kph': 9.7,
     'wind_degree': 80,
     'wind_dir': 'E',
     'pressure_mb': 1013.0,
     'pressure_in': 29.92,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 59,
     'cloud': 4,
     'feelslike_c': 38.3,
     'feelslike_f': 101.0,
     'windchill_c': 32.0,
     'windchill_f': 89.7,
     'heatindex_c': 38.3,
     'heatindex_f': 101.0,
     'dewpoint_c': 24.1,
     'dewpoint_f': 75.3,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 7.0,
     'gust_kph': 11.2,
     'uv': 7.2,
     'short_rad': 526.3,
     'diff_rad': 74.82,
     'dni': 495.36,
     'gti': 471.05},
    {'time_epoch': 1777651200,
     'time': '2026-05-01 12:00',
     'temp_c': 32.8,
     'temp_f': 91.0,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 6.9,
     'wind_kph': 11.2,
     'wind_degree': 75,
     'wind_dir': 'ENE',
     'pressure_mb': 1013.0,
     'pressure_in': 29.9,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 61,
     'cloud': 1,
     'feelslike_c': 40.1,
     'feelslike_f': 104.2,
     'windchill_c': 32.8,
     'windchill_f': 91.0,
     'heatindex_c': 40.1,
     'heatindex_f': 104.2,
     'dewpoint_c': 25.0,
     'dewpoint_f': 77.0,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 8.0,
     'gust_kph': 12.9,
     'uv': 10.1,
     'short_rad': 618.02,
     'diff_rad': 79.0,
     'dni': 683.06,
     'gti': 562.71},
    {'time_epoch': 1777654800,
     'time': '2026-05-01 13:00',
     'temp_c': 32.8,
     'temp_f': 91.0,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 8.3,
     'wind_kph': 13.3,
     'wind_degree': 58,
     'wind_dir': 'ENE',
     'pressure_mb': 1012.0,
     'pressure_in': 29.88,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 63,
     'cloud': 0,
     'feelslike_c': 40.5,
     'feelslike_f': 105.0,
     'windchill_c': 32.8,
     'windchill_f': 91.0,
     'heatindex_c': 40.5,
     'heatindex_f': 105.0,
     'dewpoint_c': 25.5,
     'dewpoint_f': 77.9,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 9.5,
     'gust_kph': 15.3,
     'uv': 11.6,
     'short_rad': 692.11,
     'diff_rad': 81.85,
     'dni': 984.14,
     'gti': 653.45},
    {'time_epoch': 1777658400,
     'time': '2026-05-01 14:00',
     'temp_c': 32.3,
     'temp_f': 90.1,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 11.2,
     'wind_kph': 18.0,
     'wind_degree': 50,
     'wind_dir': 'NE',
     'pressure_mb': 1011.0,
     'pressure_in': 29.85,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 66,
     'cloud': 0,
     'feelslike_c': 39.7,
     'feelslike_f': 103.4,
     'windchill_c': 32.3,
     'windchill_f': 90.1,
     'heatindex_c': 39.7,
     'heatindex_f': 103.4,
     'dewpoint_c': 25.6,
     'dewpoint_f': 78.0,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 12.9,
     'gust_kph': 20.7,
     'uv': 11.5,
     'short_rad': 745.58,
     'diff_rad': 83.78,
     'dni': 1591.44,
     'gti': 762.76},
    {'time_epoch': 1777662000,
     'time': '2026-05-01 15:00',
     'temp_c': 31.5,
     'temp_f': 88.7,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 14.1,
     'wind_kph': 22.7,
     'wind_degree': 45,
     'wind_dir': 'NE',
     'pressure_mb': 1010.0,
     'pressure_in': 29.84,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 67,
     'cloud': 0,
     'feelslike_c': 38.1,
     'feelslike_f': 100.5,
     'windchill_c': 31.5,
     'windchill_f': 88.7,
     'heatindex_c': 38.1,
     'heatindex_f': 100.5,
     'dewpoint_c': 25.0,
     'dewpoint_f': 77.1,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 16.2,
     'gust_kph': 26.1,
     'uv': 9.6,
     'short_rad': 965.66,
     'diff_rad': 91.59,
     'dni': 4592.41,
     'gti': 1268.96},
    {'time_epoch': 1777665600,
     'time': '2026-05-01 16:00',
     'temp_c': 30.4,
     'temp_f': 86.8,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 16.6,
     'wind_kph': 26.6,
     'wind_degree': 44,
     'wind_dir': 'NE',
     'pressure_mb': 1010.0,
     'pressure_in': 29.83,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 69,
     'cloud': 0,
     'feelslike_c': 36.0,
     'feelslike_f': 96.8,
     'windchill_c': 30.4,
     'windchill_f': 86.8,
     'heatindex_c': 36.0,
     'heatindex_f': 96.8,
     'dewpoint_c': 24.4,
     'dewpoint_f': 76.0,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 19.0,
     'gust_kph': 30.6,
     'uv': 6.8,
     'short_rad': 909.3,
     'diff_rad': 89.72,
     'dni': 0.0,
     'gti': 93.42},
    {'time_epoch': 1777669200,
     'time': '2026-05-01 17:00',
     'temp_c': 29.4,
     'temp_f': 85.0,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 15.0,
     'wind_kph': 24.1,
     'wind_degree': 49,
     'wind_dir': 'NE',
     'pressure_mb': 1010.0,
     'pressure_in': 29.83,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 72,
     'cloud': 1,
     'feelslike_c': 34.1,
     'feelslike_f': 93.4,
     'windchill_c': 29.4,
     'windchill_f': 85.0,
     'heatindex_c': 34.1,
     'heatindex_f': 93.4,
     'dewpoint_c': 23.7,
     'dewpoint_f': 74.7,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 17.2,
     'gust_kph': 27.8,
     'uv': 3.7,
     'short_rad': 834.44,
     'diff_rad': 86.65,
     'dni': 0.0,
     'gti': 89.87},
    {'time_epoch': 1777672800,
     'time': '2026-05-01 18:00',
     'temp_c': 28.5,
     'temp_f': 83.2,
     'is_day': 1,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'wind_mph': 11.9,
     'wind_kph': 19.1,
     'wind_degree': 59,
     'wind_dir': 'ENE',
     'pressure_mb': 1011.0,
     'pressure_in': 29.85,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 74,
     'cloud': 2,
     'feelslike_c': 32.4,
     'feelslike_f': 90.3,
     'windchill_c': 28.5,
     'windchill_f': 83.2,
     'heatindex_c': 32.4,
     'heatindex_f': 90.3,
     'dewpoint_c': 23.2,
     'dewpoint_f': 73.8,
     'will_it_rain': 0,
     'chance_of_rain': 0,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 14.6,
     'gust_kph': 23.5,
     'uv': 1.3,
     'short_rad': 744.12,
     'diff_rad': 82.85,
     'dni': 0.0,
     'gti': 85.5},
    {'time_epoch': 1777676400,
     'time': '2026-05-01 19:00',
     'temp_c': 28.3,
     'temp_f': 82.9,
     'is_day': 0,
     'condition': {'text': 'Partly cloudy',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png',
      'code': 1003},

In [5]:
forecast = weather_data['forecast']
forecast_3_days_summary = []

for day in forecast['forecastday']:
    forecast_3_days_summary.append(f"{day['date']}: High {day['day']['maxtemp_f']}F, Low {day['day']['mintemp_f']}F - {day['day']['condition']['text']}")

In [6]:
forecast_3_days_summary

['2026-05-01: High 92.7F, Low 72.9F - Sunny',
 '2026-05-02: High 90.2F, Low 72.9F - Sunny',
 '2026-05-03: High 87.8F, Low 77.1F - Patchy rain nearby']

In [7]:
forecast_3_days_summary = []

for day in forecast['forecastday']:
    format_day = datetime.strptime(day['date'], '%Y-%m-%d')
    formated_date = format_day.strftime('%A, %B %#d')
    forecast_3_days_summary.append(f"{formated_date}: High {day['day']['maxtemp_f']}F / Low {day['day']['mintemp_f']}F - {day['day']['condition']['text']}")

In [8]:
forecast_3_days_summary

['Friday, May 1: High 92.7F / Low 72.9F - Sunny',
 'Saturday, May 2: High 90.2F / Low 72.9F - Sunny',
 'Sunday, May 3: High 87.8F / Low 77.1F - Patchy rain nearby']

In [9]:
API_URL = "https://api.weatherapi.com/v1/astronomy.json"

<h2>One function to build summary of Weather Report</h2>

In [10]:
def get_data(url: str, parameters: dict):
    data = None
    response = requests.get(url, params=parameters)
    
    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()
    else:
        print(f"Error fetching data.\n Response: {response.status_code}")
    return data

In [11]:
def get_city_data(city: str, key=API_KEY):
    city_summary = {}
    parameters = {'key':key, 'q':city, 'days': 3}
    current_url = f"https://api.weatherapi.com/v1/current.json"
    forecast_url = f"https://api.weatherapi.com/v1/forecast.json"
    astronomy_url = f"https://api.weatherapi.com/v1/astronomy.json"
    
    current = get_data(current_url, parameters)
    forecast = get_data(forecast_url, parameters)
    astronomy = get_data(astronomy_url, parameters)
    
    city_name = current['location']['name']
    current_values = current['current']
    
    forecast_3_days_summary = []
    forecast_values = forecast['forecast']['forecastday']
    for day in forecast_values:
        format_day = datetime.strptime(day['date'], '%Y-%m-%d')
        formated_date = format_day.strftime('%A, %B %#d')
        forecast_3_days_summary.append(f"{formated_date}: High {day['day']['maxtemp_f']}F / Low {day['day']['mintemp_f']}F - {day['day']['condition']['text']}")
        
    astronomy_values = astronomy['astronomy']['astro']

    city_summary = {
        'city': city_name,
        'temp_f': current_values['temp_f'],
        'conditions': current_values['condition']['text'],
        'humidity': current_values['humidity'],
        'forecast': forecast_3_days_summary,
        'sunrise': astronomy_values['sunrise'],
        'sunset': astronomy_values['sunset'],
        'moon_phase': astronomy_values['moon_phase']
        }
    
    return city_summary

In [12]:
cities = [
    "New York City", "Los Angeles", "Chicago", "Houston", "Miami", 
    "Phoenix", "San Francisco", "Seattle", "Austin", "Denver",
    "Ciudad de Mexico", "Buenos Aires", "São Paulo", "Bogotá", "Lima",
    "Santiago", "Medellín", "Guadalajara", "Monterrey", "Quito"
]

In [13]:
summary = []
for city in cities:
    summary.append(get_city_data(city))

In [14]:
df = pd.DataFrame(summary)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        20 non-null     object
 1   temp_f      20 non-null     float64
 2   conditions  20 non-null     object
 3   humidity    20 non-null     int64
 4   forecast    20 non-null     object
 5   sunrise     20 non-null     object
 6   sunset      20 non-null     object
 7   moon_phase  20 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB

In [16]:
df[['city','temp_f']]

                  city  temp_f
0             New York    55.9
1          Los Angeles    69.1
2              Chicago    45.0
3              Houston    59.7
4                Miami    82.9
5              Phoenix    89.1
6        San Francisco    62.1
7              Seattle    71.1
8               Austin    57.9
9               Denver    60.1
10  Ciudad De Huitzuco    97.8
11        Buenos Aires    63.0
12           Sao Paulo    75.6
13              Bogotá    64.4
14                Lima    68.8
15            Santiago    57.4
16            Medellín    68.5
17         Guadalajara    91.8
18           Monterrey    77.9
19               Quito    57.2

In [17]:
df

,city,temp_f,conditions,humidity,forecast,sunrise,sunset,moon_phase
0,New York,55.9,Sunny,57,"[Friday, May 1: High 70.7F / Low 42.1F - Sunny...",05:55 AM,07:52 PM,Full Moon
1,Los Angeles,69.1,Sunny,61,"[Friday, May 1: High 78.1F / Low 54.9F - Partl...",06:04 AM,07:37 PM,Full Moon
2,Chicago,45.0,Partly cloudy,58,"[Friday, May 1: High 49.6F / Low 38.7F - Patch...",05:47 AM,07:50 PM,Full Moon
3,Houston,59.7,Mist,100,"[Friday, May 1: High 64.6F / Low 58.1F - Heavy...",06:39 AM,07:59 PM,Full Moon
4,Miami,82.9,Sunny,63,"[Friday, May 1: High 89.4F / Low 68.4F - Sunny...",06:44 AM,07:52 PM,Full Moon
5,Phoenix,89.1,Sunny,17,"[Friday, May 1: High 95.4F / Low 67.1F - Sunny...",05:40 AM,07:11 PM,Full Moon
6,San Francisco,62.1,Partly cloudy,70,"[Friday, May 1: High 63.7F / Low 51.8F - Cloud...",06:14 AM,08:00 PM,Full Moon
7,Seattle,71.1,Sunny,39,"[Friday, May 1: High 73.8F / Low 49.3F - Sunny...",05:52 AM,08:22 PM,Full Moon
8,Austin,57.9,Light rain,90,"[Friday, May 1: High 61.3F / Low 56.1F - Heavy...",06:48 AM,08:09 PM,Full Moon
9,Denver,60.1,Partly cloudy,15,"[Friday, May 1: High 61.1F / Low 40.9F - Patch...",06:00 AM,07:54 PM,Full Moon
10,Ciudad De Huitzuco,97.8,Sunny,17,"[Friday, May 1: High 100.4F / Low 69.3F - Sunn...",06:10 AM,06:59 PM,Full Moon
11,Buenos Aires,63.0,Partly Cloudy,83,"[Friday, May 1: High 71.4F / Low 57.8F - Patch...",07:31 AM,06:12 PM,Full Moon
12,Sao Paulo,75.6,Partly Cloudy,78,"[Friday, May 1: High 79.1F / Low 65.6F - Patch...",06:27 AM,05:40 PM,Full Moon
13,Bogotá,64.4,Partly cloudy,60,"[Friday, May 1: High 66.2F / Low 48.3F - Patch...",05:45 AM,06:02 PM,Full Moon
14,Lima,68.8,Partly Cloudy,80,"[Friday, May 1: High 71.1F / Low 66.4F - Sunny...",06:15 AM,05:56 PM,Full Moon
15,Santiago,57.4,Clear,77,"[Friday, May 1: High 68.3F / Low 53.9F - Partl...",07:17 AM,06:02 PM,Full Moon
16,Medellín,68.5,Patchy rain nearby,73,"[Friday, May 1: High 76.8F / Low 55.1F - Moder...",05:49 AM,06:09 PM,Full Moon
17,Guadalajara,91.8,Partly cloudy,13,"[Friday, May 1: High 93.0F / Low 61.7F - Sunny...",06:23 AM,07:18 PM,Full Moon
18,Monterrey,77.9,Partly Cloudy,60,"[Friday, May 1: High 79.2F / Low 65.5F - Patch...",06:04 AM,07:13 PM,Full Moon
19,Quito,57.2,Patchy rain nearby,71,"[Friday, May 1: High 63.1F / Low 46.7F - Patch...",06:08 AM,06:14 PM,Full Moon